build:
  uri: https://github.com/wildfly/quickstart.git
  ref: 33.x
  contextDir: opentelemetry-tracing
deploy:
  replicas: 1
  env:
    - name: OTEL_COLLECTOR_HOST
      value: "opentelemetrycollector"
