build:
  uri: https://github.com/emmartins/quickstart.git
  ref: helmset
  contextDir: helloworld
deploy:
  replicas: 1
  env:
    - name: userName
      value: "{{ .Values.userName }}"
    - name: userPassword
      value: "{{ .Values.userPassword }}"