name: WildFly EJB Timer Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - <quickstart-path>/ejb-timer/**'
      - .github/workflows/quickstart_ci.yml

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-timer
      DEPLOYMENT_DIR: webapp
      TEST_PROVISIONED_SERVER: true
